<?php
	const SEARCH_PHOTO_ERROR_CASE_NUM_3 = 3;
	const SEARCH_PHOTO_ERROR_CASE_NUM_4 = 4;
	const SEARCH_PHOTO_ERROR_CASE_NUM_6 = 6;
	const SEARCH_PHOTO_ERROR_CASE_NUM_7 = 7;
	const SEARCH_PHOTO_ERROR_CASE_NUM_8 = 8;
	const CHECK_VALUE_IN_GET_ARRAY_CASE_NUM_0 = 0;
	const CHECK_VALUE_IN_GET_ARRAY_CASE_NUM_1 = 1;
	const CHECK_VALUE_IN_GET_ARRAY_CASE_NUM_2 = 2;
	const CHECK_VALUE_IN_GET_ARRAY_CASE_NUM_3 = 3;
	const CHECK_VALUE_IN_GET_ARRAY_CASE_NUM_4 = 4;
	const CHECK_VALUE_IN_GET_ARRAY_CASE_NUM_6 = 6;
	const CHECK_VALUE_IN_GET_ARRAY_CASE_NUM_7 = 7;
	const CHECK_VALUE_IN_GET_ARRAY_CASE_NUM_8 = 8;